### ISSUE TITLE
Error in README - no namespace called forum.config

### ISSUE THREAD

**Issue by ghost** [Herzult/HerzultForumBundle#18]
I get this error when trying to configure the forum in app/config/config.yml as per the README:

InvalidArgumentException: There is no extension able to load the configuration for "forum.config" (in /srv/http/neverside/Symfony/app/config/config.yml). Looked for namespace "forum.config", found "framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "assetic", "sensio_framework_extra", "jms_security_extra", "acme_hello", "acme_test", "forum", "doctrine_mongodb", "acme_demo", "web_profiler", "sensio_distribution"

replacing "forum.config" with "forum" makes it not complain, but I'm still not sure if this is right.

**Comment by Herzult** [comment]
Yes, you're right, this is remaining from an old Symfony version.
