### ISSUE TITLE
Exception rendering Topic:list.html.twig

### ISSUE THREAD

**Issue by ghost** [Herzult/HerzultForumBundle#20]
```
An exception has been thrown during the rendering of a template 
("Warning: class_parents(): Class Acme\Model\Topic does not exist 
and could not be loaded in /srv/http/myapp/Symfony/vendor/doctrine/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
line 223") in "HerzultForumBundle:Forum:index.html.twig" at line 10.
```

I get this error trying to view Forum:index. I installed per the new documentation w/ FOSUserBundle. I'm still new to Symfony so any help would be greatly appreciated!

**Comment by ghost** [comment]
@Herzult What am I missing here? Do data fixtures need to be loaded? Do I need to run some doctrine commands from app/console?

**Comment by Korto-Maltez** [comment]
I have got the same error,

Have you find any answer??

K

**Comment by ghost** [comment]
No answer. Although I gave up trying to use this bundle.
