### ISSUE TITLE
can't make it work...

### ISSUE THREAD

**Issue by panosru** [Herzult/HerzultForumBundle#27]
Hello, maybe I'm stupid I don't know... but I simply can't make it work... maybe a better documentation or more detailed would be great... I also have a related post **[here](http://forum.symfony-project.org/viewtopic.php?f=23&t=38146)**

Also ODM documentation is missing :/

**Comment by dbykadorov** [comment]
@panosru how did you solve the forum problem? Do you have integrated PHPBB? Or use this bundle (it works for me, but have just basic features).

**Comment by panosru** [comment]
Hi, no unfortunately I gave up on this bundle but didn't tried to integrate phpbb yet...
