### ISSUE TITLE
Implementing the bundle

### ISSUE THREAD

**Issue by chrishey** [Herzult/HerzultForumBundle#35]
Hi,
I have installed the Herzult Fourm Bundle (https://github.com/Herzult/HerzultForumBundle) into my Symfony 2 application, added the calls in the app kernel and auto load and extended the base classes.  The problem i am having is i have a site layout that is applied to every page in the application and i want to render the forum within this.

I am very new to Symfony and PHP, but i have tried a few ways to get this working.  I have a controller method set up that will render the forum page correctly which is set through the normal routing configuration, i can also set it up so that is routes to the index method in the Forum controller in the Herzult forum bundle.  However this renders the default styles for the forum index page and is not contained by the layout i require.

Can someone provide me with an example of how to implement the forum and integrate it into a site?  A simple example would point me in the right direction.

Thanks

**Comment by Blackskyliner** [comment]
The forum uses a base.html.twig by default.

So you could overload this template in your app/Resources/view folder.
There you extend your Layout which you are using and you are done.

If you are not so familiar with Twig templates, yet I would suggest you to read up the symfony.com Documentation about Templating in SF2.
