### ISSUE TITLE
Bundle missing on packagist

### ISSUE THREAD

**Issue by stof** [Herzult/HerzultForumBundle#44]
The bundle has a composer.json file but is not registered on packagist, making it harder to use it through composer. Technically, anybody could register it but it is considered a bad practice to register it when you are not the maintainer (as it means you would  be the maintainer on packagist instead of the real maintainer). So please register it on packagist (it is simply a matter of creating an account (if you don't have one) and submit the url of the github repo

**Comment by Herzult** [comment]
Fixed: http://packagist.org/packages/herzult/forum-bundle
Thanks.

**Comment by stof** [comment]
Btw, the autoloading and target-dir settings are wrong in the composer.json, making it broken.

**Comment by Herzult** [comment]
Better?

**Comment by stof** [comment]
Yes. Btw, I think some requirements are missing. I doubt the bundle can be used with only Pagerfanta (there should be a dependency to FrameworkBundle for instance)

**Comment by stof** [comment]
Btw, you should probably enable the packagist hook on github (and trigger it manually once to let Packagist know about it if you don't do a push soon)

**Comment by Herzult** [comment]
Done
